// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuespsclhurnlcoxdfxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51ZXNwc2NsaHVybmxjb3hkZnhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MDQxOTgsImV4cCI6MjA2NzE4MDE5OH0.PiAMFmbkqre05ig8YBRxkpwvbV3Wu_YEzX8rtGmEJWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});